export const mock = {
  entry: {
    device_id: "web",
    device_category: "web",
    device_model: "web",
    device_type: "web",
    device_so: "Chrome",
    format: "json",
    device_manufacturer: "generic",
    authpn: "webclient",
    authpt: "tfg1h3j4k6fd7",
    api_version: "v5.93",
    region: "mexico",
    HKS: "web61144bb49d549",
    user_id: "54343080",
    date_from: "20240612000000",
    date_to: "20240613240000",
    quantity: "1",
  },
  response: {
    channels: [
      {
        id: "20861",
        number: "1",
        name: "UNO TV",
        hd: false,
        image:
          "https://clarovideocdn5.clarovideo.net/PELICULAS/UNOTV/EXPORTACION_WEB/SS/UNOTV_t-290x163.png",
        group_id: "1147425",
        liveref: "noticias_unotv_hd_mx",
        epg_url: "TV",
        source_uri: "",
        provider_metadata_id: 2,
        provider_metadata_name: "NAGRA",
        group: {
          common: {
            id: "1147425",
            title: "UNO TV",
            title_episode: null,
            title_uri: "UNO-TV",
            title_original: "UNO TV",
            description: "NOTICIAS_UNOTV_HD_MX",
            description_large: "NOTICIAS_UNOTV_HD_MX",
            short_description: null,
            image_large:
              "https://clarovideocdn9.clarovideo.net/PELICULAS/UNOTV/EXPORTACION_WEB/SS/UNOTVWHORIZONTAL.jpg?size=675x380",
            image_medium:
              "https://clarovideocdn7.clarovideo.net/PELICULAS/UNOTV/EXPORTACION_WEB/SS/UNOTVWVERTICAL.jpg?size=200x300",
            image_small:
              "https://clarovideocdn9.clarovideo.net/PELICULAS/UNOTV/EXPORTACION_WEB/SS/UNOTVWHORIZONTAL.jpg?size=290x163",
            image_still: null,
            image_background:
              "https://clarovideocdn9.clarovideo.net/PELICULAS/UNOTV/EXPORTACION_WEB/CLEAN/UNOTV_e-1280x720.jpg",
            url_imagen_t1:
              "https://clarovideocdn0.clarovideo.net/PELICULAS/UNOTV/EXPORTACION_WEB/CLEAN/UNOTVWVERTICAL.jpg?size=200x300",
            url_imagen_t2:
              "https://clarovideocdn2.clarovideo.net/PELICULAS/UNOTV/EXPORTACION_WEB/CLEAN/UNOTVWHORIZONTAL.jpg?size=290x163",
            image_base_horizontal:
              "https://clarovideocdn6.clarovideo.net/PELICULAS/UNOTV/EXPORTACION_WEB/SS/UNOTVWHORIZONTAL.jpg",
            image_base_vertical:
              "https://clarovideocdn4.clarovideo.net/PELICULAS/UNOTV/EXPORTACION_WEB/SS/UNOTVWVERTICAL.jpg",
            image_base_square:
              "https://clarovideocdn4.clarovideo.net/PELICULAS/UNOTV/EXPORTACION_WEB/SS/UNOTVWCUADRADO.jpg",
            image_clean_horizontal:
              "https://clarovideocdn9.clarovideo.net/PELICULAS/UNOTV/EXPORTACION_WEB/CLEAN/UNOTVWHORIZONTAL.jpg",
            image_clean_vertical:
              "https://clarovideocdn7.clarovideo.net/PELICULAS/UNOTV/EXPORTACION_WEB/CLEAN/UNOTVWVERTICAL.jpg",
            image_clean_square:
              "https://clarovideocdn7.clarovideo.net/PELICULAS/UNOTV/EXPORTACION_WEB/CLEAN/UNOTVWCUADRADO.jpg",
            image_sprites:
              "https://clarovideocdn0.clarovideo.net/PELICULAS/UNOTV/EXPORTACION_WEB/SPRITES/UNOTV-SPRITEBAR.jpg",
            image_frames:
              "https://clarovideocdn6.clarovideo.net/PELICULAS/UNOTV/EXPORTACION_WEB/SPRITES/UNOTV-00h-00m-00s-00f.jpg",
            image_trickplay: "",
            image_external: null,
            duration: null,
            date: "03/04/2024",
            year: null,
            preview: "false",
            season_number: null,
            episode_number: null,
            format_types: "susc",
            live_enabled: "1",
            live_type: "1",
            live_ref: "noticias_unotv_hd_mx",
            source_uri: "",
            timeshift: null,
            votes_average: 4,
            rating_code: "G",
            proveedor_name: "AMCO",
            proveedor_code: "amco",
            encoder_tecnology: {
              id: "3",
              desc: "HARMONIC_VOS",
            },
            recorder_technology: {
              id: null,
              desc: null,
            },
            resource_name: null,
            rollingcreditstime: null,
            rollingcreditstimedb: null,
            is_series: false,
            channel_number: "1",
          },
        },
        events: [
          {
            channel_id: "20861",
            source_uri: "",
            id: "2066396045",
            name: "Las Noticias En Claro",
            description:
              "Noticiero De Referencia Obligada En El Periodismo En México Y El Mundo. La Trayectoria De Su Conductor, José Cárdenas Ha Convertido A Este Espacio De Noticias En Consulta Obligada Para Los Especialistas En Temas De Política. Espacio Informativo Que Destaca Por El Puntual Análisis De Temas Coyunturales En Voz De Colaboradores Del Nivel De Jesús Silva Herzog-Márquez; María Amparo Casar, Alejandra Cullen, Carlos Elizondo Mayer-Serra Y José Antonio Valdés Peña.",
            talent: null,
            date_begin: "2024/06/11 23:00:00",
            date_end: "2024/06/12 12:00:00",
            unix_begin: 1718172000,
            unix_end: 1718215200,
            duration: "12:00:00",
            language: "esp",
            type: "0",
            group_id: null,
            confirmado: null,
            id_empleado: null,
            tms_id: null,
            event_alf_id: "79dd209caaeb",
            ext_ncont_id: "42040398932",
            ext_nevt_id: "79dd209caaeb",
            ext_actors: null,
            ext_director: null,
            ext_year: null,
            ext_country: null,
            ext_original_name: "Las Noticias En Claro",
            ext_ep_original_name: null,
            ext_series_id: "042040374631",
            ext_season_id: "24",
            ext_episode_id: "301",
            ext_language: "spa",
            ext_serie_short_desc: null,
            ext_serie_desc: null,
            image_base_horizontal: "",
            image_base_vertical: "",
            image_base_square: "",
            ext_eventimage_name: "",
            ext_eventimage_name_base: "",
            ext_catchup: "0",
            ext_startover: "0",
            ext_recordable: "0",
            parental_rating: "+12",
            aud_stereo: "0",
            aud_dolby: "0",
            vid_black_and_white: "0",
            dvb_content: "Noticias",
            user_content: null,
            group_rel: null,
            gmt: -6,
          },
          {
            channel_id: "20861",
            source_uri: "",
            id: "2066396055",
            name: "Uno Noticias",
            description:
              "Noticiero Que Destaca Por La Presencia Siempre Fresca De Sus Conductores Cuya Trayectoria En El Periodismo Garantiza Credibilidad Y Certeza En Los Contenidos. Las Noticias Nacionales E Internacionales, Así Como Las Tendencias En Redes Sociales Y Espectáculos Tienen El Mejor Escaparate En Este Espacio Informativo.",
            talent: null,
            date_begin: "2024/06/12 12:00:00",
            date_end: "2024/06/12 14:00:00",
            unix_begin: 1718215200,
            unix_end: 1718222400,
            duration: "02:00:00",
            language: "esp",
            type: "0",
            group_id: null,
            confirmado: null,
            id_empleado: null,
            tms_id: null,
            event_alf_id: "d27b4296c147",
            ext_ncont_id: "823013543225",
            ext_nevt_id: "d27b4296c147",
            ext_actors: null,
            ext_director: null,
            ext_year: null,
            ext_country: null,
            ext_original_name: "Uno Noticias",
            ext_ep_original_name: null,
            ext_series_id: "823013518924",
            ext_season_id: "24",
            ext_episode_id: "301",
            ext_language: "spa",
            ext_serie_short_desc: null,
            ext_serie_desc: null,
            image_base_horizontal: "",
            image_base_vertical: "",
            image_base_square: "",
            ext_eventimage_name: "",
            ext_eventimage_name_base: "",
            ext_catchup: "0",
            ext_startover: "0",
            ext_recordable: "0",
            parental_rating: "+12",
            aud_stereo: "0",
            aud_dolby: "0",
            vid_black_and_white: "0",
            dvb_content: "Noticias",
            user_content: null,
            group_rel: null,
            gmt: -6,
          },
          {
            channel_id: "20861",
            source_uri: "",
            id: "2066396064",
            name: "Uno Noticias",
            description:
              "Noticiero Que Destaca Por La Presencia Siempre Fresca De Sus Conductores Cuya Trayectoria En El Periodismo Garantiza Credibilidad Y Certeza En Los Contenidos. Las Noticias Nacionales E Internacionales, Así Como Las Tendencias En Redes Sociales Y Espectáculos Tienen El Mejor Escaparate En Este Espacio Informativo.",
            talent: null,
            date_begin: "2024/06/12 14:00:00",
            date_end: "2024/06/12 18:00:00",
            unix_begin: 1718222400,
            unix_end: 1718236800,
            duration: "04:00:00",
            language: "esp",
            type: "0",
            group_id: null,
            confirmado: null,
            id_empleado: null,
            tms_id: null,
            event_alf_id: "767d709651d6",
            ext_ncont_id: "823013543226",
            ext_nevt_id: "767d709651d6",
            ext_actors: null,
            ext_director: null,
            ext_year: null,
            ext_country: null,
            ext_original_name: "Uno Noticias",
            ext_ep_original_name: null,
            ext_series_id: "823013518924",
            ext_season_id: "24",
            ext_episode_id: "302",
            ext_language: "spa",
            ext_serie_short_desc: null,
            ext_serie_desc: null,
            image_base_horizontal: "",
            image_base_vertical: "",
            image_base_square: "",
            ext_eventimage_name: "",
            ext_eventimage_name_base: "",
            ext_catchup: "0",
            ext_startover: "0",
            ext_recordable: "0",
            parental_rating: "+12",
            aud_stereo: "0",
            aud_dolby: "0",
            vid_black_and_white: "0",
            dvb_content: "Noticias",
            user_content: null,
            group_rel: null,
            gmt: -6,
          },
          {
            channel_id: "20861",
            source_uri: "",
            id: "2066396072",
            name: "Las Noticias En Claro",
            description:
              "Noticiero De Referencia Obligada En El Periodismo En México Y El Mundo. La Trayectoria De Su Conductor, José Cárdenas Ha Convertido A Este Espacio De Noticias En Consulta Obligada Para Los Especialistas En Temas De Política. Espacio Informativo Que Destaca Por El Puntual Análisis De Temas Coyunturales En Voz De Colaboradores Del Nivel De Jesús Silva Herzog-Márquez; María Amparo Casar, Alejandra Cullen, Carlos Elizondo Mayer-Serra Y José Antonio Valdés Peña.",
            talent: null,
            date_begin: "2024/06/12 18:00:00",
            date_end: "2024/06/12 21:30:00",
            unix_begin: 1718236800,
            unix_end: 1718249400,
            duration: "03:30:00",
            language: "esp",
            type: "0",
            group_id: null,
            confirmado: null,
            id_empleado: null,
            tms_id: null,
            event_alf_id: "89b0c56c10cc",
            ext_ncont_id: "42040398933",
            ext_nevt_id: "89b0c56c10cc",
            ext_actors: null,
            ext_director: null,
            ext_year: null,
            ext_country: null,
            ext_original_name: "Las Noticias En Claro",
            ext_ep_original_name: null,
            ext_series_id: "042040374631",
            ext_season_id: "24",
            ext_episode_id: "302",
            ext_language: "spa",
            ext_serie_short_desc: null,
            ext_serie_desc: null,
            image_base_horizontal: "",
            image_base_vertical: "",
            image_base_square: "",
            ext_eventimage_name: "",
            ext_eventimage_name_base: "",
            ext_catchup: "0",
            ext_startover: "0",
            ext_recordable: "0",
            parental_rating: "+12",
            aud_stereo: "0",
            aud_dolby: "0",
            vid_black_and_white: "0",
            dvb_content: "Noticias",
            user_content: null,
            group_rel: null,
            gmt: -6,
          },
          {
            channel_id: "20861",
            source_uri: "",
            id: "2066396081",
            name: "Las Noticias En Claro",
            description:
              "Noticiero De Referencia Obligada En El Periodismo En México Y El Mundo. La Trayectoria De Su Conductor, José Cárdenas Ha Convertido A Este Espacio De Noticias En Consulta Obligada Para Los Especialistas En Temas De Política. Espacio Informativo Que Destaca Por El Puntual Análisis De Temas Coyunturales En Voz De Colaboradores Del Nivel De Jesús Silva Herzog-Márquez; María Amparo Casar, Alejandra Cullen, Carlos Elizondo Mayer-Serra Y José Antonio Valdés Peña.",
            talent: null,
            date_begin: "2024/06/12 21:30:00",
            date_end: "2024/06/13 01:00:00",
            unix_begin: 1718249400,
            unix_end: 1718258400,
            duration: "02:30:00",
            language: "esp",
            type: "0",
            group_id: null,
            confirmado: null,
            id_empleado: null,
            tms_id: null,
            event_alf_id: "7a7d6797895d",
            ext_ncont_id: "42040398934",
            ext_nevt_id: "7a7d6797895d",
            ext_actors: null,
            ext_director: null,
            ext_year: null,
            ext_country: null,
            ext_original_name: "Las Noticias En Claro",
            ext_ep_original_name: null,
            ext_series_id: "042040374631",
            ext_season_id: "24",
            ext_episode_id: "303",
            ext_language: "spa",
            ext_serie_short_desc: null,
            ext_serie_desc: null,
            image_base_horizontal: "",
            image_base_vertical: "",
            image_base_square: "",
            ext_eventimage_name: "",
            ext_eventimage_name_base: "",
            ext_catchup: "0",
            ext_startover: "0",
            ext_recordable: "0",
            parental_rating: "+12",
            aud_stereo: "0",
            aud_dolby: "0",
            vid_black_and_white: "0",
            dvb_content: "Noticias",
            user_content: null,
            group_rel: null,
            gmt: -6,
          },
        ],
      },
      {
        id: "20861",
        number: "1",
        name: "UNO TV",
        hd: false,
        image:
          "https://clarovideocdn5.clarovideo.net/PELICULAS/UNOTV/EXPORTACION_WEB/SS/UNOTV_t-290x163.png",
        group_id: "1147425",
        liveref: "noticias_unotv_hd_mx",
        epg_url: "TV",
        source_uri: "",
        provider_metadata_id: 2,
        provider_metadata_name: "NAGRA",
        group: {
          common: {
            id: "1147425",
            title: "UNO TV",
            title_episode: null,
            title_uri: "UNO-TV",
            title_original: "UNO TV",
            description: "NOTICIAS_UNOTV_HD_MX",
            description_large: "NOTICIAS_UNOTV_HD_MX",
            short_description: null,
            image_large:
              "https://clarovideocdn9.clarovideo.net/PELICULAS/UNOTV/EXPORTACION_WEB/SS/UNOTVWHORIZONTAL.jpg?size=675x380",
            image_medium:
              "https://clarovideocdn7.clarovideo.net/PELICULAS/UNOTV/EXPORTACION_WEB/SS/UNOTVWVERTICAL.jpg?size=200x300",
            image_small:
              "https://clarovideocdn9.clarovideo.net/PELICULAS/UNOTV/EXPORTACION_WEB/SS/UNOTVWHORIZONTAL.jpg?size=290x163",
            image_still: null,
            image_background:
              "https://clarovideocdn9.clarovideo.net/PELICULAS/UNOTV/EXPORTACION_WEB/CLEAN/UNOTV_e-1280x720.jpg",
            url_imagen_t1:
              "https://clarovideocdn0.clarovideo.net/PELICULAS/UNOTV/EXPORTACION_WEB/CLEAN/UNOTVWVERTICAL.jpg?size=200x300",
            url_imagen_t2:
              "https://clarovideocdn2.clarovideo.net/PELICULAS/UNOTV/EXPORTACION_WEB/CLEAN/UNOTVWHORIZONTAL.jpg?size=290x163",
            image_base_horizontal:
              "https://clarovideocdn6.clarovideo.net/PELICULAS/UNOTV/EXPORTACION_WEB/SS/UNOTVWHORIZONTAL.jpg",
            image_base_vertical:
              "https://clarovideocdn4.clarovideo.net/PELICULAS/UNOTV/EXPORTACION_WEB/SS/UNOTVWVERTICAL.jpg",
            image_base_square:
              "https://clarovideocdn4.clarovideo.net/PELICULAS/UNOTV/EXPORTACION_WEB/SS/UNOTVWCUADRADO.jpg",
            image_clean_horizontal:
              "https://clarovideocdn9.clarovideo.net/PELICULAS/UNOTV/EXPORTACION_WEB/CLEAN/UNOTVWHORIZONTAL.jpg",
            image_clean_vertical:
              "https://clarovideocdn7.clarovideo.net/PELICULAS/UNOTV/EXPORTACION_WEB/CLEAN/UNOTVWVERTICAL.jpg",
            image_clean_square:
              "https://clarovideocdn7.clarovideo.net/PELICULAS/UNOTV/EXPORTACION_WEB/CLEAN/UNOTVWCUADRADO.jpg",
            image_sprites:
              "https://clarovideocdn0.clarovideo.net/PELICULAS/UNOTV/EXPORTACION_WEB/SPRITES/UNOTV-SPRITEBAR.jpg",
            image_frames:
              "https://clarovideocdn6.clarovideo.net/PELICULAS/UNOTV/EXPORTACION_WEB/SPRITES/UNOTV-00h-00m-00s-00f.jpg",
            image_trickplay: "",
            image_external: null,
            duration: null,
            date: "03/04/2024",
            year: null,
            preview: "false",
            season_number: null,
            episode_number: null,
            format_types: "susc",
            live_enabled: "1",
            live_type: "1",
            live_ref: "noticias_unotv_hd_mx",
            source_uri: "",
            timeshift: null,
            votes_average: 4,
            rating_code: "G",
            proveedor_name: "AMCO",
            proveedor_code: "amco",
            encoder_tecnology: {
              id: "3",
              desc: "HARMONIC_VOS",
            },
            recorder_technology: {
              id: null,
              desc: null,
            },
            resource_name: null,
            rollingcreditstime: null,
            rollingcreditstimedb: null,
            is_series: false,
            channel_number: "1",
          },
        },
        events: [
          {
            channel_id: "20861",
            source_uri: "",
            id: "2066396045",
            name: "Las Noticias En Claro",
            description:
              "Noticiero De Referencia Obligada En El Periodismo En México Y El Mundo. La Trayectoria De Su Conductor, José Cárdenas Ha Convertido A Este Espacio De Noticias En Consulta Obligada Para Los Especialistas En Temas De Política. Espacio Informativo Que Destaca Por El Puntual Análisis De Temas Coyunturales En Voz De Colaboradores Del Nivel De Jesús Silva Herzog-Márquez; María Amparo Casar, Alejandra Cullen, Carlos Elizondo Mayer-Serra Y José Antonio Valdés Peña.",
            talent: null,
            date_begin: "2024/06/12 00:00:00",
            date_end: "2024/06/12 12:00:00",
            unix_begin: 1718172000,
            unix_end: 1718215200,
            duration: "12:00:00",
            language: "esp",
            type: "0",
            group_id: null,
            confirmado: null,
            id_empleado: null,
            tms_id: null,
            event_alf_id: "79dd209caaeb",
            ext_ncont_id: "42040398932",
            ext_nevt_id: "79dd209caaeb",
            ext_actors: null,
            ext_director: null,
            ext_year: null,
            ext_country: null,
            ext_original_name: "Las Noticias En Claro",
            ext_ep_original_name: null,
            ext_series_id: "042040374631",
            ext_season_id: "24",
            ext_episode_id: "301",
            ext_language: "spa",
            ext_serie_short_desc: null,
            ext_serie_desc: null,
            image_base_horizontal: "",
            image_base_vertical: "",
            image_base_square: "",
            ext_eventimage_name: "",
            ext_eventimage_name_base: "",
            ext_catchup: "0",
            ext_startover: "0",
            ext_recordable: "0",
            parental_rating: "+12",
            aud_stereo: "0",
            aud_dolby: "0",
            vid_black_and_white: "0",
            dvb_content: "Noticias",
            user_content: null,
            group_rel: null,
            gmt: -6,
          },
          {
            channel_id: "20861",
            source_uri: "",
            id: "2066396055",
            name: "Uno Noticias",
            description:
              "Noticiero Que Destaca Por La Presencia Siempre Fresca De Sus Conductores Cuya Trayectoria En El Periodismo Garantiza Credibilidad Y Certeza En Los Contenidos. Las Noticias Nacionales E Internacionales, Así Como Las Tendencias En Redes Sociales Y Espectáculos Tienen El Mejor Escaparate En Este Espacio Informativo.",
            talent: null,
            date_begin: "2024/06/12 12:00:00",
            date_end: "2024/06/12 14:00:00",
            unix_begin: 1718215200,
            unix_end: 1718222400,
            duration: "02:00:00",
            language: "esp",
            type: "0",
            group_id: null,
            confirmado: null,
            id_empleado: null,
            tms_id: null,
            event_alf_id: "d27b4296c147",
            ext_ncont_id: "823013543225",
            ext_nevt_id: "d27b4296c147",
            ext_actors: null,
            ext_director: null,
            ext_year: null,
            ext_country: null,
            ext_original_name: "Uno Noticias",
            ext_ep_original_name: null,
            ext_series_id: "823013518924",
            ext_season_id: "24",
            ext_episode_id: "301",
            ext_language: "spa",
            ext_serie_short_desc: null,
            ext_serie_desc: null,
            image_base_horizontal: "",
            image_base_vertical: "",
            image_base_square: "",
            ext_eventimage_name: "",
            ext_eventimage_name_base: "",
            ext_catchup: "0",
            ext_startover: "0",
            ext_recordable: "0",
            parental_rating: "+12",
            aud_stereo: "0",
            aud_dolby: "0",
            vid_black_and_white: "0",
            dvb_content: "Noticias",
            user_content: null,
            group_rel: null,
            gmt: -6,
          },
          {
            channel_id: "20861",
            source_uri: "",
            id: "2066396064",
            name: "Uno Noticias",
            description:
              "Noticiero Que Destaca Por La Presencia Siempre Fresca De Sus Conductores Cuya Trayectoria En El Periodismo Garantiza Credibilidad Y Certeza En Los Contenidos. Las Noticias Nacionales E Internacionales, Así Como Las Tendencias En Redes Sociales Y Espectáculos Tienen El Mejor Escaparate En Este Espacio Informativo.",
            talent: null,
            date_begin: "2024/06/12 14:00:00",
            date_end: "2024/06/12 18:00:00",
            unix_begin: 1718222400,
            unix_end: 1718236800,
            duration: "04:00:00",
            language: "esp",
            type: "0",
            group_id: null,
            confirmado: null,
            id_empleado: null,
            tms_id: null,
            event_alf_id: "767d709651d6",
            ext_ncont_id: "823013543226",
            ext_nevt_id: "767d709651d6",
            ext_actors: null,
            ext_director: null,
            ext_year: null,
            ext_country: null,
            ext_original_name: "Uno Noticias",
            ext_ep_original_name: null,
            ext_series_id: "823013518924",
            ext_season_id: "24",
            ext_episode_id: "302",
            ext_language: "spa",
            ext_serie_short_desc: null,
            ext_serie_desc: null,
            image_base_horizontal: "",
            image_base_vertical: "",
            image_base_square: "",
            ext_eventimage_name: "",
            ext_eventimage_name_base: "",
            ext_catchup: "0",
            ext_startover: "0",
            ext_recordable: "0",
            parental_rating: "+12",
            aud_stereo: "0",
            aud_dolby: "0",
            vid_black_and_white: "0",
            dvb_content: "Noticias",
            user_content: null,
            group_rel: null,
            gmt: -6,
          },
          {
            channel_id: "20861",
            source_uri: "",
            id: "2066396072",
            name: "Las Noticias En Claro",
            description:
              "Noticiero De Referencia Obligada En El Periodismo En México Y El Mundo. La Trayectoria De Su Conductor, José Cárdenas Ha Convertido A Este Espacio De Noticias En Consulta Obligada Para Los Especialistas En Temas De Política. Espacio Informativo Que Destaca Por El Puntual Análisis De Temas Coyunturales En Voz De Colaboradores Del Nivel De Jesús Silva Herzog-Márquez; María Amparo Casar, Alejandra Cullen, Carlos Elizondo Mayer-Serra Y José Antonio Valdés Peña.",
            talent: null,
            date_begin: "2024/06/12 18:00:00",
            date_end: "2024/06/12 21:30:00",
            unix_begin: 1718236800,
            unix_end: 1718249400,
            duration: "03:30:00",
            language: "esp",
            type: "0",
            group_id: null,
            confirmado: null,
            id_empleado: null,
            tms_id: null,
            event_alf_id: "89b0c56c10cc",
            ext_ncont_id: "42040398933",
            ext_nevt_id: "89b0c56c10cc",
            ext_actors: null,
            ext_director: null,
            ext_year: null,
            ext_country: null,
            ext_original_name: "Las Noticias En Claro",
            ext_ep_original_name: null,
            ext_series_id: "042040374631",
            ext_season_id: "24",
            ext_episode_id: "302",
            ext_language: "spa",
            ext_serie_short_desc: null,
            ext_serie_desc: null,
            image_base_horizontal: "",
            image_base_vertical: "",
            image_base_square: "",
            ext_eventimage_name: "",
            ext_eventimage_name_base: "",
            ext_catchup: "0",
            ext_startover: "0",
            ext_recordable: "0",
            parental_rating: "+12",
            aud_stereo: "0",
            aud_dolby: "0",
            vid_black_and_white: "0",
            dvb_content: "Noticias",
            user_content: null,
            group_rel: null,
            gmt: -6,
          },
          {
            channel_id: "20861",
            source_uri: "",
            id: "2066396081",
            name: "Las Noticias En Claro",
            description:
              "Noticiero De Referencia Obligada En El Periodismo En México Y El Mundo. La Trayectoria De Su Conductor, José Cárdenas Ha Convertido A Este Espacio De Noticias En Consulta Obligada Para Los Especialistas En Temas De Política. Espacio Informativo Que Destaca Por El Puntual Análisis De Temas Coyunturales En Voz De Colaboradores Del Nivel De Jesús Silva Herzog-Márquez; María Amparo Casar, Alejandra Cullen, Carlos Elizondo Mayer-Serra Y José Antonio Valdés Peña.",
            talent: null,
            date_begin: "2024/06/12 21:30:00",
            date_end: "2024/06/13 00:00:00",
            unix_begin: 1718249400,
            unix_end: 1718258400,
            duration: "02:30:00",
            language: "esp",
            type: "0",
            group_id: null,
            confirmado: null,
            id_empleado: null,
            tms_id: null,
            event_alf_id: "7a7d6797895d",
            ext_ncont_id: "42040398934",
            ext_nevt_id: "7a7d6797895d",
            ext_actors: null,
            ext_director: null,
            ext_year: null,
            ext_country: null,
            ext_original_name: "Las Noticias En Claro",
            ext_ep_original_name: null,
            ext_series_id: "042040374631",
            ext_season_id: "24",
            ext_episode_id: "303",
            ext_language: "spa",
            ext_serie_short_desc: null,
            ext_serie_desc: null,
            image_base_horizontal: "",
            image_base_vertical: "",
            image_base_square: "",
            ext_eventimage_name: "",
            ext_eventimage_name_base: "",
            ext_catchup: "0",
            ext_startover: "0",
            ext_recordable: "0",
            parental_rating: "+12",
            aud_stereo: "0",
            aud_dolby: "0",
            vid_black_and_white: "0",
            dvb_content: "Noticias",
            user_content: null,
            group_rel: null,
            gmt: -6,
          },
        ],
      },
    ],
    total: 26,
  },
  status: "0",
  msg: "OK",
};
